trigger: 
  branches:
    include:
    - '*'
  tags:
    include:
    - '*SNAPSHOT*'
    - '*RELEASE*'
    - '*RC*'  
  paths:
    exclude:
    - '*.md'
    - 'img/*'
    - 'charts/*'

resources:
- repo: self
